version: '3.8'

services:
  shop:
    container_name: shop
    build: ./shop
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./shop:/usr/src/shop/
    networks:
      - shop_db_network
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev


  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - shop_db_network
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

networks:
  shop_db_network:


volumes:
    db: